cmake_minimum_required(VERSION 3.4)
project(solver_application)
add_executable(solver_application equation.cpp)
target_link_libraries(solver_application formatter_ex solver_lib)

install(TARGETS solver_application RUNTIME DESTINATION bin)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "fedor")
set(CPACK_SOURCE_IGNORE_FILES  "\.cmake;/build/;/\.git/;/\.gitignore;/\.github/")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/..;/")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
include(CPack)
